spring.application.name=FlightWeatherTracker

api.imgw.metar=https://aviation-api.imgw.pl/data/last?params=metar&format=json&count=1
api.imgw.taf=https://aviation-api.imgw.pl/data/last?params=taf&format=json&count=1
api.imgw.sigmet=https://aviation-api.imgw.pl/data/last?params=new_sigmet&format=json