spring.application.name=FlightWeatherTracker

api.imgw.metar=https://aviation-api.imgw.pl/data/last?params=metar,taf&format=json&count=1
api.imgw.taf=https://aviation-api.imgw.pl/data/last?params=metar,taf&format=json&count=1
api.imgw.sigmet=https://aviation-api.imgw.pl/data/last?params=new_sigmet&format=json

api.open-meteo=https://api.open-meteo.com/v1/forecast?latitude=%s&longitude=%s&hourly=temperature_2m,dew_point_2m,wind_speed_10m,wind_direction_10m,wind_gusts_10m,visibility,cloud_cover_low,cloud_cover_mid,cloud_cover_high,surface_pressure,snowfall,snow_depth,rain,showers&current=temperature_2m,wind_speed_10m,wind_direction_10m,wind_gusts_10m,precipitation,rain,showers,snowfall,cloud_cover,surface_pressure&timezone=auto&past_days=2&forecast_days=3
airports.config.path=config/airports_config.json
api.responses.dir=data/

spring.datasource.url=jdbc:postgresql://localhost:54350/flight_weather_db
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
